### PR TITLE
Implementation and initial design of piece editor

### PR DESCRIPTION
**Pull request by ValleSten**
This PR contains the initial draft of the Piece editor and should be merged in conjunction with [this PR from the back-end](https://github.com/ChessVariants/ChessVariantsAPI/pull/28). I believe all functionality has been implemented, but it does look like 💩 I'm happy to get some input on the layout/design of it all (not my strong suit). I believe the design is quite self-explanatory once you run the program. The editor is accessible by pressing the bottom button on the main menu or by a "/pieceEditor" extension to the url.

There are four main files that has been created here:

## EditorBoard
This is basically the same as GameBoard, but some functionality has been exchanged, for instance that the the piece can be placed anywhere at all times.

## EditorSidePage
This is the component to the right containing all the controllers for the the piece. Here patterns can be added, the board resized and other attributes of a Piece changed.

## PatternList
This is the component to the right, a list of all current patterns of the Piece.

## EditorService
This is essentially the same as GameService, it handles all communication with the back-end.

I am quite unsure of where the connection with the EditorHub of the back-end should be established. Right now it is created directly in App, in the same way as the connection to GameHub is established. However, this means that there is a constant connection to the EditorHub, even when it's not in use. I'd appreciate some input on this :)

Happy reviewing!

### CODE REVIEW

**Comment by Bobbelty** [comment]
Well done! I have just a few design inputs that could help improve the user experience. 

1. Use a divider to separate different parts of the "create a new piece" side menu. Could for example be to divide them in to the following: Regular patterns, jump patterns, board size settings etc. I think this could help as it looks compact at the moment. 

2. The left side menu could be improved by allowing the user to alter the values instead of having to remove the pattern. Either by using +/- to increment / decrease the values or textfields for input. 

3. I don't know how easy this would be but it would be nice if movement and capture patterns were differentiated in color to make it easier to see how the piece would work. What is your opinion on this?

The functionality behind the editor works well and if you do not agree with the comments above or think they could be implemented in a future task let me know and I will approve the PR!:)

**Comment by Bobbelty** [comment]
Another very small thing: the MUI component ThemeProvider can be removed as I added it to the root of the application so it is not necessary to use it further down.

**Comment by ValleSten** [comment]
I have reviewed your comments and made some changes accordingly :D

The divider helped a lot to make the design a lot more tidy and structured, thanks for that! I have also moved around some of the components and separated the file into two subfiles `PatternList` and `PatternInputs` as well as included a button to reset the whole piece.

Good idea to have the values of the fields in the patterns be alterable directly from the list. I've made some buttons that allows this as well as a button to remove all current patterns in the top. 

My initial idea was to do something similar to your idea with different colors of the squares. However, I believe it would require to alter the existing or to create an additional Square class. It would be a nice feature, but with respect to time, I decided to exclude it.

Moreover, I have added logic that allows each user to have their separate editor which is something that I had missed previously. These changes are found in the [this PR for the backend.](url) that should be merged in conjunction with this one.

**Comment by Bobbelty** [comment]
Good job! The editor looks much better now!

**Review by Bobbelty — APPROVED** [review]
Looks good! Well done! I have now approved the merge

**Pull request merged**
