### PR TITLE
Lobby functionality, authentication, 404 and unauthorized pages.

### PR DESCRIPTION
**Pull request by sjohan99**
## NOTE!
This PR should be merged in conjunction with https://github.com/ChessVariants/ChessVariantsAPI/pull/19

## Lobby / Setup
You can now create and join games via the UI. When creating a game you need to supply a variant, and then you'll be redirected to a lobby. In the lobby the player gets a game-id which they can send to the other player for them to join, or they can copy a link to clipboard. In the lobby only the creator can start the game and swap colors between the players. In order to do all these you need to be logged in.

## Authentication
Using the login side we can log in as a registered user, or as a guest. In both of these cases we receive a JWT from the server which is saved as a cookie. `GameService` now uses that cookie to authenticate requests to the server. In addition to this we also receive the user's username upon login, which is also stored as a cookie. Both of these use the npm package `universal-cookie` to handle cookies.

## `GameService.ts` and `GameBoard.tsx`
GameService now defines two naming conventions for methods `sendXXX` and `requestXXX`. The `send` methods only make an RPC call to the server without waiting for a response, it may or may not receive a response eventually through events sent by the server. The ´request´ methods actually return a `Promise` of the result. Read more about this [here](https://github.com/ChessVariants/ChessVariantsAPI/pull/19)

Additionally, some interfaces have been defined for data coming from the server, such as `GameState` and `Colors`. This simplifies working with data from the server as we can simply treat them as typescript objects immediatelly upon reception. `GameBoard.tsx` previously used a type called `State` as the type for the data received when the game state has updated, but now instead uses the interface `GameState`.

## PageNotFound and Unauthorized
There are now two pages for 404 responses and unauthorized responses. Any non-existing paths will redirect to PageNotFound. In cases where you try to do something unauthorized, such as enter URL to a match you're not part of, you will be redirected to the unauthorized page.

## Bugs / Refactoring
A good few bugs have been solved as well and some code refactored.

### CODE REVIEW

**Comment by Bobbelty** [comment]
Looks very good to me! However, there are some smaller changes that could improve the quality:

1 (bug). This bug results in a situation where the name of the first player is not displayed and no players can join. I was able to replicate this bug by logging in as a guest, then instantly clicking "create game". The lobby will now have no players and it will not be possible to join. If I however, refresh the page after logging in, everything works perfectly.

2. When the admin leaves, the UI of the second player that is now the new admin still the old (not admin) UI. This can be fixed by slightly altering the use of isAdmin prop by removing it from the input parameter and instead using useState with gameservice event.

**Comment by sjohan99** [comment]
## 1.
When logging in and going directly to creating a match would result in an empty lobby and game. This bug was caused by a failure to establish a connection with the gamehub (due to the user not being logged in).

In order to fix this issue we need to recreate the connection with the hub using the newly received access token. This turned out to be easier said than done. In the end the solution involves adding a change listener to the cookies, and when we get a new access token we'll recreate the GameService instance (and thus the connection).

In order to persist the cookie change listener I created CookieService.ts. This was because otherwise when we created a new Cookies object, it would be another instance from the one App.tsx subscribes to.

In addition, I've added more rigorous authentication measures in App.tsx. It will now redirect the user to an error page if the servers are offline, and correctly wait until connection has been established otherwise.

MatchPage.tsx also checks if the game service is actually connected before rendering. If that is not the case, that means the authentication processed has failed, and it will instead render a redirection page for the user to log in. This situation appears when a user enters a match-link directly into the browser, without being authenticated.

## 2.
I agree this should be done, although I think we can fix that in a future PR. Fairly low priority imo!

**Comment by sjohan99** [comment]
If you agree then just approve this request. I'll merge after fixing issues with corresponding backend PR!

**Review by Bobbelty — APPROVED** [review]
Good job!

**Pull request merged**
